import type {
  CharacterConfigDto,
  CharacterDto,
  CharacterBulkCreationJobDto,
  CharacterManagementDto,
  SaveCharacterRequest,
} from "@enjo/shared";
import { randomUUID } from "node:crypto";
import { LLMError, LLMTimeoutError } from "../llm/provider.js";
import type { ModelProfileRepository } from "../model-profiles/model-profile-repository.js";
import type { CharacterRepository } from "./character-repository.js";
import type { Character, SaveCharacter } from "./character.js";
import {
  CharacterPersonaParseError,
  type CharacterPersonaGenerator,
} from "./character-generator.js";

/**
 * Strips the persona and behaviour fields.
 *
 * Ordinary timeline/profile responses stay lightweight. The editor uses the
 * separate config DTO below; provider credentials are never included.
 */
export function toCharacterDto(character: Character): CharacterDto {
  return {
    id: character.id,
    handle: character.handle,
    displayName: character.displayName,
    description: character.description,
    ...(character.avatarUrl ? { avatarUrl: character.avatarUrl } : {}),
  };
}

export function toCharacterConfigDto(character: Character): CharacterConfigDto {
  return {
    ...toCharacterDto(character),
    rolePrompt: character.rolePrompt,
    tonePrompt: character.tonePrompt,
    ...(character.dialectPrompt ? { dialectPrompt: character.dialectPrompt } : {}),
    interests: character.interests,
    activityLevel: character.activityLevel,
    responseProbability: character.responseProbability,
    replyProbability: character.replyProbability,
    quoteProbability: character.quoteProbability,
    influence: character.influence,
    modelProfileId: character.modelProfileId,
  };
}

export function toCharacterManagementDto(
  character: Character,
): CharacterManagementDto {
  return {
    ...toCharacterDto(character),
    activityLevel: character.activityLevel,
    responseProbability: character.responseProbability,
    replyProbability: character.replyProbability,
    quoteProbability: character.quoteProbability,
    influence: character.influence,
    modelProfileId: character.modelProfileId,
  };
}

export class CharacterNotFoundError extends Error {
  constructor(id: string) {
    super(`character "${id}" not found`);
    this.name = "CharacterNotFoundError";
  }
}

export class CharacterHandleConflictError extends Error {
  constructor(handle: string) {
    super(`handle "@${handle}" is already in use`);
    this.name = "CharacterHandleConflictError";
  }
}

export class ModelProfileNotFoundError extends Error {
  constructor(id: string) {
    super(`model profile "${id}" not found`);
    this.name = "ModelProfileNotFoundError";
  }
}

export class CharacterGenerationError extends Error {
  constructor(options?: { cause?: unknown }) {
    super("characters could not be generated by the LLM", options);
    this.name = "CharacterGenerationError";
  }
}

export class CharacterService {
  private readonly bulkCreationJobs = new Map<string, CharacterBulkCreationJobDto>();

  constructor(
    private readonly characters: CharacterRepository,
    private readonly modelProfiles: ModelProfileRepository,
    private readonly personaGenerator: CharacterPersonaGenerator,
    private readonly random: () => number = Math.random,
  ) {}

  async listDtos(): Promise<CharacterDto[]> {
    const all = await this.characters.findAll();
    return all.map(toCharacterDto);
  }

  async listManagementDtos(): Promise<CharacterManagementDto[]> {
    const all = await this.characters.findAll();
    return all.map(toCharacterManagementDto);
  }

  async findDto(id: string): Promise<CharacterDto | null> {
    const character = await this.characters.findById(id);
    return character ? toCharacterDto(character) : null;
  }

  async findConfigDto(id: string): Promise<CharacterConfigDto | null> {
    const character = await this.characters.findById(id);
    return character ? toCharacterConfigDto(character) : null;
  }

  async create(input: SaveCharacterRequest): Promise<CharacterConfigDto> {
    await this.assertModelProfile(input.modelProfileId);
    await this.assertHandleAvailable(input.handle);
    const character = await this.characters.create(randomUUID(), toSaveCharacter(input));
    return toCharacterConfigDto(character);
  }

  async createMany(
    count: number,
    onProgress?: (completed: number) => void,
  ): Promise<CharacterDto[]> {
    const [defaultProfile] = await this.modelProfiles.findAll();
    if (!defaultProfile) throw new ModelProfileNotFoundError("default");

    let personas;
    try {
      personas = await this.personaGenerator.generate(count, defaultProfile, onProgress);
    } catch (cause) {
      throw new CharacterGenerationError({ cause });
    }

    const entries = personas.map((persona) => {
      const id = randomUUID();
      const suffix = id.replaceAll("-", "").slice(0, 8);
      return {
        id,
        input: {
          handle: `character_${suffix}`,
          displayName: persona.displayName,
          description: persona.description,
          rolePrompt: persona.rolePrompt,
          tonePrompt: persona.tonePrompt,
          ...(persona.dialectPrompt ? { dialectPrompt: persona.dialectPrompt } : {}),
          interests: persona.interests,
          activityLevel: randomProbability(this.random),
          responseProbability: randomProbability(this.random),
          replyProbability: randomProbability(this.random),
          quoteProbability: randomProbability(this.random),
          influence: randomProbability(this.random),
          modelProfileId: defaultProfile.id,
        },
      };
    });
    const created = await this.characters.createMany(entries);
    return created.map(toCharacterDto);
  }

  startCreateMany(count: number): CharacterBulkCreationJobDto {
    const id = randomUUID();
    const job: CharacterBulkCreationJobDto = {
      id,
      status: "generating",
      completed: 0,
      total: count,
      createdCount: 0,
    };
    this.bulkCreationJobs.set(id, job);
    this.pruneBulkCreationJobs();

    void this.createMany(count, (completed) => {
      this.bulkCreationJobs.set(id, {
        ...job,
        status: completed >= count ? "saving" : "generating",
        completed,
      });
    })
      .then((created) => {
        this.bulkCreationJobs.set(id, {
          ...job,
          status: "completed",
          completed: count,
          createdCount: created.length,
        });
      })
      .catch((error: unknown) => {
        const current = this.bulkCreationJobs.get(id) ?? job;
        this.bulkCreationJobs.set(id, {
          ...current,
          status: "failed",
          error: characterGenerationFailureMessage(error),
        });
      });

    return job;
  }

  findBulkCreationJob(id: string): CharacterBulkCreationJobDto | null {
    return this.bulkCreationJobs.get(id) ?? null;
  }

  private pruneBulkCreationJobs(): void {
    const maximumJobs = 100;
    while (this.bulkCreationJobs.size > maximumJobs) {
      const oldestId = this.bulkCreationJobs.keys().next().value as string | undefined;
      if (!oldestId) return;
      this.bulkCreationJobs.delete(oldestId);
    }
  }

  async update(id: string, input: SaveCharacterRequest): Promise<CharacterConfigDto> {
    const existing = await this.characters.findById(id);
    if (!existing) throw new CharacterNotFoundError(id);

    await this.assertModelProfile(input.modelProfileId);
    await this.assertHandleAvailable(input.handle, id);
    const character = await this.characters.update(id, toSaveCharacter(input));
    return toCharacterConfigDto(character);
  }

  async delete(id: string): Promise<string> {
    if (!(await this.characters.findById(id))) {
      throw new CharacterNotFoundError(id);
    }
    await this.characters.delete(id);
    return id;
  }

  async deleteMany(ids: string[]): Promise<string[]> {
    const uniqueIds = [...new Set(ids)];
    const existing = await this.characters.findByIds(uniqueIds);
    const deletedIds = existing.map((character) => character.id);
    await this.characters.deleteMany(deletedIds);
    return deletedIds;
  }

  private async assertModelProfile(id: string): Promise<void> {
    if (!(await this.modelProfiles.findById(id))) throw new ModelProfileNotFoundError(id);
  }

  private async assertHandleAvailable(handle: string, currentId?: string): Promise<void> {
    const existing = await this.characters.findByHandle(handle);
    if (existing && existing.id !== currentId) throw new CharacterHandleConflictError(handle);
  }
}

function randomProbability(random: () => number): number {
  return Math.round(Math.min(1, Math.max(0, random())) * 100) / 100;
}

function characterGenerationFailureMessage(error: unknown): string {
  const cause = error instanceof CharacterGenerationError ? error.cause : error;
  if (cause instanceof LLMTimeoutError) {
    return `LLMの応答がタイムアウトしました: ${safeErrorDetail(cause.message)}`;
  }
  if (cause instanceof LLMError) {
    return `LLM APIの呼び出しに失敗しました: ${safeErrorDetail(cause.message)}`;
  }
  if (cause instanceof CharacterPersonaParseError) return cause.message;
  if (cause instanceof Error) {
    return `キャラクター生成処理でエラーが発生しました: ${safeErrorDetail(cause.message)}`;
  }
  return "LLMによるキャラクター生成に失敗しました。";
}

function safeErrorDetail(message: string): string {
  const normalized = message.replace(/\s+/gu, " ").trim();
  return Array.from(normalized).slice(0, 240).join("");
}

function toSaveCharacter(input: SaveCharacterRequest): SaveCharacter {
  return {
    handle: input.handle,
    displayName: input.displayName,
    description: input.description,
    rolePrompt: input.rolePrompt,
    tonePrompt: input.tonePrompt,
    ...(input.dialectPrompt ? { dialectPrompt: input.dialectPrompt } : {}),
    interests: input.interests,
    activityLevel: input.activityLevel,
    responseProbability: input.responseProbability,
    replyProbability: input.replyProbability,
    quoteProbability: input.quoteProbability,
    influence: input.influence,
    modelProfileId: input.modelProfileId,
    ...(input.avatarUrl ? { avatarUrl: input.avatarUrl } : {}),
  };
}
