steps:
  - id: build-backend-amd64
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    args:
      - build
      - --platform=linux/amd64
      - --file=apps/backend/Dockerfile
      - --tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/brickr-staging/backend:${_IMAGE_TAG}
      - .

  - id: build-frontend-amd64
    name: gcr.io/cloud-builders/docker
    waitFor: ["-"]
    args:
      - build
      - --platform=linux/amd64
      - --file=apps/frontend/Dockerfile
      - --tag=asia-northeast1-docker.pkg.dev/$PROJECT_ID/brickr-staging/frontend:${_IMAGE_TAG}
      - .

images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/brickr-staging/backend:${_IMAGE_TAG}
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/brickr-staging/frontend:${_IMAGE_TAG}

substitutions:
  _IMAGE_TAG: staging

options:
  logging: CLOUD_LOGGING_ONLY
