/**
 * Lifecycle status of a scheduled background event.
 *
 * Allowed transitions (enforced at the worker layer):
 *   pending     → processing  (atomic claim by a worker)
 *   processing  → completed   (worker finished successfully)
 *   processing  → failed      (worker encountered an error)
 *   failed      → pending     (retry, up to maxAttempts)
 *   pending     → cancelled   (room archived/deleted, or cast removed/banned)
 *   processing  → cancelled   (rare: room archived while worker holds the lock)
 */
export type EventStatus =
  | "pending"
  | "processing"
  | "completed"
  | "failed"
  | "cancelled";

/**
 * The set of event types the worker knows how to execute (design spec §9).
 *
 * Stored as a plain string in the DB so new types can be added without a
 * schema migration, but the domain layer uses this union for type safety.
 */
export type ScheduledEventType =
  | "character.respond"
  | "character.join.request"
  | "character.join.welcome"
  | "thread.revive"
  | "room.review"
  | "room.analysis.refresh";

/**
 * A single entry in the background event queue (design spec §9).
 *
 * The worker polls for `pending` events whose `scheduledAt` has arrived,
 * atomically claims them by setting `status = 'processing'` and recording
 * `lockedBy` / `lockedAt`, then executes and marks them `completed` or
 * `failed`.
 */
export type ScheduledEvent = {
  id: string;
  type: ScheduledEventType;
  status: EventStatus;
  scheduledAt: Date;

  /** The room this event belongs to. */
  roomId: string | null;
  /** The post that triggered this event, if applicable. */
  postId: string | null;
  /** The thread root of the triggering post, if applicable. */
  threadRootId: string | null;
  /** The character this event is for, if applicable. */
  characterId: string | null;

  /** Worker that currently holds the lock. Null when not processing. */
  lockedBy: string | null;
  /** When the lock was acquired. Used to reclaim events from crashed workers. */
  lockedAt: Date | null;

  /** Number of execution attempts so far. */
  attempts: number;
  /** Last error message, for debugging failed events. */
  lastError: string | null;

  createdAt: Date;
  updatedAt: Date;
};

/**
 * Input for creating a new scheduled event.
 *
 * `id` is generated by the caller so the caller can reference it before the
 * insert completes (consistent with the Post pattern in this codebase).
 */
export type NewScheduledEvent = {
  id: string;
  type: ScheduledEventType;
  scheduledAt: Date;
  roomId?: string | null;
  postId?: string | null;
  threadRootId?: string | null;
  characterId?: string | null;
};
