/** Post domain model. User posts, character posts, replies and quotes are all Posts. */
export type Post = {
  id: string;
  roomId: string;
  /** Character id, or the id of the user account that wrote the post (§66.3). */
  authorId: string;
  content: string;
  imageUrl?: string;
  /** Handles referenced in the body, without the leading "@". */
  mentions: string[];
  replyTo: string | null;
  quoteOf: string | null;
  /**
   * Root of this post's thread; a top-level post is its own root. Denormalised
   * for feed paging (Brickr-ux-refine §8.3).
   */
  threadRootId: string;
  /**
   * Newest activity in the thread when this row is a root, own creation time
   * when it is a reply.
   */
  threadActivityAt: Date;
  createdAt: Date;
};

/**
 * Everything needed to persist a new post.
 *
 * The id is generated by the caller rather than the database, because a
 * top-level post has to write `threadRootId = id` in the same insert (§8.3).
 *
 * `threadRootId` is deliberately absent: it is derived from `replyTo` inside the
 * publishing transaction (§8.4), so no caller can hand over a root it read
 * earlier and no longer holds.
 */
export type NewPost = {
  id: string;
  roomId: string;
  authorId: string;
  content: string;
  imageUrl?: string;
  mentions: string[];
  replyTo?: string | null;
  quoteOf?: string | null;
};
